### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by StevenArai** [wixette/font-to-3d-models#4]
the cmd con:
```
Z:\blender2.79\blender-2.79-windows64\font-to-3d-models-main>..\blender.exe -b -P font_to_3d_models.py -- -f ./Roboto-Regular.ttf -o ./out -s 65 -e 90
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: Z:\blender2.79\blender-2.79-windows64\2.79\python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Z:\blender2.79\blender-2.79-windows64\font-to-3d-models-main\font_to_3d_models.py", line 38
    print(f'Generating 3D model for glyph {char_name}')
                                                     ^
SyntaxError: invalid syntax

Blender quit
```
with system Administratior identity.
gtx 750
i7 - 3770s
12gb ram
win11 21H2 22000.1219

**Comment by wixette** [comment]
It seems the Python version shipped with blender-2.79 does not support Python's template string syntax. You can either use Blender v3.x to run the script or modify the python code by eliminating all those print() statements.

E.g., when running with Blender v3.4.1, the Python version is 3.10.8:

```
'C:\Program Files\Blender Foundation\Blender 3.4\blender' -b -P .\font_to_3d_models.py -- -h
Blender 3.4.1 (hash 55485cb379f7 built 2022-12-20 01:51:19)
Read prefs: C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Python version: 3.10.8 (main, Oct 18 2022, 21:01:35) [MSC v.1928 64 bit (AMD64)]
```

**Comment by StevenArai** [comment]
im using microsoft store version blender, so i cant call blender.exe with cmd, are there any way to run it while blender is running? i tried to import .py into it like a plugin, and nothing happened, then i opened blender terminal window and trying to  run it, then i realize this terninal is definitely not a cmd or powershell, then i stucked here...

**Comment by StevenArai** [comment]
im using microsoft store version blender, so i cant call blender.exe with cmd, are there any way to run it while blender is running? i tried to import .py into it like a plugin, and nothing happened, then i opened blender terminal window and trying to  run it, then i realize this terninal is definitely not a cmd or powershell, then i stucked here...
